### PR TITLE
link tag requires rel attribute for css to work

### PR DESCRIPTION
**Pull request by waldyrious**
(you might want to change that blue background, though ;)

### CODE REVIEW

**Comment by leostera** [comment]
@waldyrious, thanks, I just found your PR's. I did thou fix this while I was re-styling, let me know what you think! :)

**Comment by waldyrious** [comment]
Looks cool! I wouldn't have the whole interface in monospaced font, though, or at least I'd style the actual command examples differently (e.g. a text or background color) to differentiate them. And perhaps remove the bullet or replace them with an ASCII character, using either a [`:before`](http://ryansechrest.com/2012/11/change-your-list-bullet-to-a-custom-character-in-css/) hack or the brand-new [`@counter-style`](https://hacks.mozilla.org/2015/02/introducing-counter-styles/) rule :)

Also, I still think the changes in PR #2 would make sense, i.e. move the blockquotes to the left and the commands to the right to make the tree structure more visible.

**Comment by leostera** [comment]
@waldyrious, how does it look now after https://github.com/leostera/tldr.js/commit/441055be6840b151914d1c7b30dbb7c8d04b33d7 ?

Made sure to use xterm256 colors, and kept the content compact. Hierarchy is clearer now via horizontal padding, and I threw in italics for the block quote since (mimicking a tldr for console client) making it grayer/lighter-coloured made it look weird.

**Comment by waldyrious** [comment]
Looks great :) I'll submit a few tweaks, but yeah, that's exactly what I meant.

**Comment by waldyrious** [comment]
Update: see #3 and #4.

**Pull request closed without merging**
